version: 1.0.{build}
image: Visual Studio 2017
skip_commits:
  files:
    - '*.md'
build_script:
- cmd: >-
    dotnet pack -c Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION% src/Pengines.Client.fsproj
test_script:
- cmd: dotnet test -f netcoreapp2.0 tests/Pengines.Client.Tests.fsproj
artifacts:
- path: src\bin\Release\Pengines.Client.1.0.%APPVEYOR_BUILD_NUMBER%.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: I4rC81ZB9RJoTnqKtW36gOFLdPDcdQoo/y2E8gG+S0teqic6Ty4eBY1h/bz6LeAs